from __future__ import print_function

import os
import subprocess
import sys
import tempfile
from unittest import TestCase


class TestTONCmdOverride(TestCase):
    def _success_cmd(self):
        python = sys.executable
        if os.name == "nt":
            return '"' + python + '" -c "import sys; sys.exit(0)"'
        return "'" + python + "' -c 'import sys; sys.exit(0)'"

    def test_cmd_override_takes_priority_over_default_tolk_handler(self):
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        env = os.environ.copy()
        existing_pythonpath = env.get("PYTHONPATH")
        if existing_pythonpath:
            env["PYTHONPATH"] = repo_root + os.pathsep + existing_pythonpath
        else:
            env["PYTHONPATH"] = repo_root

        with tempfile.TemporaryDirectory() as temp_dir:
            source_file = os.path.join(temp_dir, "override.tolk")
            helper_file = os.path.join(temp_dir, "helper.tolk")
            rule_file = os.path.join(temp_dir, "invalid.rules")
            mutant_dir = os.path.join(temp_dir, "mutants")
            output_file = os.path.join(temp_dir, "mutate.out")

            with open(source_file, "w") as f:
                f.write(
                    'import "helper"\n\n'
                    "fun sum(a: int, b: int): int {\n"
                    "    return a + b;\n"
                    "}\n\n"
                    "fun onInternalMessage() {\n"
                    "}\n"
                )

            with open(helper_file, "w") as f:
                f.write("fun helper(): int {\n    return 1;\n}\n")

            with open(rule_file, "w") as f:
                f.write("return a \\+ b; ==> return a + ;\n")

            with open(output_file, "w") as f:
                result = subprocess.call(
                    [
                        sys.executable,
                        "-m",
                        "universalmutator.genmutants",
                        source_file,
                        "tolk",
                        "--only",
                        rule_file,
                        "--cmd",
                        self._success_cmd(),
                        "--noFastCheck",
                        "--mutantDir",
                        mutant_dir,
                    ],
                    cwd=repo_root,
                    env=env,
                    stdout=f,
                    stderr=f,
                )

            self.assertEqual(result, 0)

            with open(output_file, "r") as f:
                out = f.read()

            self.assertIn("1 MUTANTS GENERATED BY RULES", out)
            self.assertIn("1 VALID MUTANTS", out)
            self.assertIn("0 INVALID MUTANTS", out)
            self.assertEqual(len(os.listdir(mutant_dir)), 1)
